---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux
  namespace: flux
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/hamtaro702/Flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux
  namespace: flux
spec:
  interval: 10m0s
  path: ./my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  validation: client
